{% set version = "3.3.9" %}

package:
  name: orange3
  version: {{ version }}

source:
  fn: Orange3-{{ version }}.tar.gz
  url: https://github.com/biolab/orange3/archive/{{ version }}.tar.gz
  md5: dcc39b94e8d06a28315b4188bbc9b705
  patches:
    - requirements.patch # conda does not yet provide scikit-learn 0.18.1

build:
  number: 0
  script:
    - python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - orange-canvas = Orange.canvas.__main__:main
  osx_is_app: True
  skip: True        # [py2k]

requirements:
  build:
    - toolchain
    - python
    - setuptools
    - numpy x.x
  run:
    - python
    - setuptools
    - numpy x.x
    - numpy         >=1.9.0
    - scipy
    - scikit-learn  >=0.18
    - bottleneck
    - chardet       >=2.3.0
    - docutils
    - xlrd          >=0.9.2
    - pyqt            4.11.*
    - pyqtgraph
    - joblib
    - keyring
    - keyrings.alt
    - dill
    - anyqt
    - python.app    # [osx]

test:
  commands:
    - python -c "import pkg_resources; pkg_resources.require('Orange3')"
    - orange-canvas --help
  imports:
    - Orange

app:
  entry: orange-canvas
  summary: 'data visualization and data analysis tool'
  icon: icon_48x48.png

about:
  home: http://orange.biolab.si/
  license: GPL3
  license_file: LICENSE
  summary: component-based data mining framework
  description: |
    Open source data visualization and data analysis for novice and expert.
    Interactive workflows with a large toolbox.
  doc_url: http://orange.biolab.si/docs/
  dev_url: https://github.com/biolab/orange3

extra:
  recipe-maintainers:
    - astaric
    - lanzagar
    - ales-erjavec
